version: '3.9'

services:
  web:
    build: .
    container_name: sistema_web
    ports:
      - "8080:80"
    volumes:
      - ./htdocs:/var/www/html

    depends_on:
      - db

  db:
  image: mysql:8.0
  container_name: sistema_db
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: sistema
    MYSQL_USER: admin
    MYSQL_PASSWORD: 1234
  volumes:
    - db_data:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d

volumes:
  db_data:
