version: '3.8'

services:
  app:
    build: .
    container_name: sistema_app
    ports:
      - "8080:80"
    volumes:
      - ./htdocs:/var/www/html
    environment:
      MYSQL_HOST: 192.168.5.50
      MYSQL_USER: facundo.figuera
      MYSQL_PASSWORD: 56812417
      MYSQL_DATABASE: sistema
    restart: unless-stopped

  backup:
    build: .
    container_name: sistema_backup
    ports:
      - "8081:80"
    volumes:
      - ./htdocs:/var/www/html
    restart: always
